### ISSUE TITLE
Hassio compatible ?

### ISSUE THREAD

**Issue by vincegre** [ezand/chirpstack-addon-repository#1]
Hi

Just discovered your repo but is it compatible with Hassio ? I don't see any ways to install it out of getting access at docker :(

Thanks

Vincèn

**Comment by ezand** [comment]
Hi @vincegre! I'm afraid it's not installable yet (hassio or hacs). I haven't had time to prioritise work on this for a while. Hopefully I will be able at some point 😺

**Comment by vincegre** [comment]
Hi @ezand Thanks for answer and I uderstand ;)
